### ISSUE TITLE
How do I deploy this?

### ISSUE THREAD

**Issue by leonoverweel** [jamy015/slack-latex-bot#2]
Could you add a Setup section to `README.md`?

**Comment by jamy015** [comment]
You don't need to deploy it, just click the *Add to Slack* button. Keep in mind that currently (due to Heroku sleeping dyno's) you might need to try the command twice at times. I will probably have time to move to another host in one or two weeks which should resolve that problem.

If you would still like to deploy your own instance, you need to register a bot on http://api.slack.com, add a slash command to the `/slack/latex` endpoint, set their tokens in the SLACK_CLIENT_ID, SLACK_CLIENT_SECRET and SLACK_VERIFICATION_TOKEN environment variables and run `bot.py` using a WSGI-compatible web server (I use [Gunicorn](http://gunicorn.org/).

I might add a SETUP.md, but the idea is that you can just click 'Add to Slack' and then you don't need to think about it anymore.
